### ISSUE TITLE
Feature Title: Enhanced Display Name Tracking for Moderation

### ISSUE THREAD

**Issue by vibinator** [EchoTools/nakama#16]
Feature Request:

Server Moderators often struggle to keep track of users who routinely alter their display names in game.

This means misconduct or rule violations can be difficult to attribute to the correct individual when their screen name is constantly changing. (when  video evidence is outdated, or contains their old name)

Proposed Solution:

Implement a slash command for moderators that allows lookup of a user's display name history within the Nakama, linked to their unique Discord ID. (Simliar to the discord "ModView")

Command Syntax:

/displayhistory [User Mention or User ID]

**Comment by thesprockee** [comment]
`/lookup` will have past display names in it. fix is in today.
