### ISSUE TITLE
Stuck unready Map 

### ISSUE THREAD

**Issue by vibinator** [EchoTools/nakama#4]
Title: Stuck unready Map: 

How to replicate it: Within Spark (or entering it manually) If you select the map type of  - Combat (Dyson, Surge,Fission,Combustion) with the Game Mode of Arena,

What is the intended result: This is an invalid format, the game shouldn't accept it

What is the actual result: It puts you into a Public Match, that is struck unready private.

What is the impact if this doesn't get fixed: If someone does this, People will keep backfilling into this match until the gameserver is stuck down by a serverhost.

Screenshots:

![image](https://github.com/EchoTools/nakama/assets/88991400/e9d87fdf-af33-4a78-a844-59f690c139e2)

**Comment by h4ck3r210** [comment]
https://github.com/EchoTools/nakama/pull/10 _should_ fix this issue.
